### PR TITLE
Raise error if browser can't open

### LINKED ISSUE #3: Ensure error if the browser can't launch
Looks like if the browser can't launch there's no error.

For the auth workflow with the cli we want to terminate the local server and fail with a clear error if that's the case.

### PR DESCRIPTION
**Pull request by mattdsteele**
Fixes #3

### CODE REVIEW

**Comment by dblock** [comment]
So I wonder if we need to `server.start` before we call `Launchy`? Then I think we do need a spec for this. Add a new set of tests for `Cli::Auth` and stub the argument to Launchy to some invalid string, it should raise an error, and terminate the web server.

**Comment by mattdsteele** [comment]
I tried running `server.start` before calling Launchy, but since WEBrick blocks the main thread, it couldn't continue executing the program; so I moved it back to where it originally was. Maybe there's a way around this? I'm not super familiar with Ruby's patterns...

File: spec/auth_spec.rb [hunk 1]
```diff
@@ -0,0 +1,17 @@
+require 'spec_helper'
+
+describe Strava do
+  describe 'auth' do
+    it 'shuts down server when launchy fails' do
+      options = { client_id: 'foo', client_secret: 'bar' }
+      expect(Launchy).to receive(:open).and_yield('failed')
+      auth = Strava::Cli::Auth.new(options)
+      # expect(auth.access_token).to raise_error
```
Comment (mattdsteele) [inline spec/auth_spec.rb]: Looking for feedback here too. I was hoping to use this assertion, but it produced an error:

```
  1) Strava auth shuts down server when launchy fails
     Failure/Error: raise "Failed to open browser to request Strava authentication. Cause: #{err}"
     
     RuntimeError:
       Failed to open browser to request Strava authentication. Cause: failed
     # ./lib/cli/auth.rb:66:in `block in get_access_token'
     # ./lib/cli/auth.rb:65:in `get_access_token'
     # ./lib/cli/auth.rb:12:in `access_token'
     # ./spec/auth_spec.rb:9:in `block (3 levels) in <top (required)>'
```

So I manually `rescue`d below. I feel like I'm missing something obvious here?

**Comment by dblock** [comment]
> I tried running `server.start` before calling Launchy, but since WEBrick blocks the main thread, it couldn't continue executing the program; so I moved it back to where it originally was. Maybe there's a way around this? I'm not super familiar with Ruby's patterns...

That makes sense. Probably that's why I didn't do it myself either. We could spawn a thread, etc., nbd.

File: spec/auth_spec.rb (hunk 1 above)
Comment (dblock) [inline spec/auth_spec.rb]: This was correct, `expect(auth.access_token).to raise_error "put the full message here"` should work

File: spec/auth_spec.rb [hunk 2]
```diff
@@ -0,0 +1,17 @@
+require 'spec_helper'
+
+describe Strava do
+  describe 'auth' do
+    it 'shuts down server when launchy fails' do
+      options = { client_id: 'foo', client_secret: 'bar' }
```
Comment (dblock) [inline spec/auth_spec.rb]: since `options` is not reused more than once, just write them into the arguments of `Strava::Cli::Auth.new`

File: lib/cli/auth.rb [hunk 3]
```diff
@@ -62,7 +62,9 @@ def get_access_token
           scope: @scope
         )
 
-        Launchy.open redirect_url
+        Launchy.open redirect_url do |err|
+          raise "Failed to open browser to request Strava authentication. Cause: #{err}"
```
Comment (dblock) [inline lib/cli/auth.rb]: There's actually a typical pattern for these errors in Ruby that I've observed, and we probably don't want to assume that the issue was to open the browser. Maybe the URL would be useful here too, since it could be the problem. How about this?

```
raise "Failed to browse to #{redirect_url}: #{err}"
```

**Review by mattdsteele — COMMENTED** [review]
Figured it out; I needed to use a block.

**Comment by dblock** [comment]
Want to help out with the (co)maintenance of this gem? Maybe make the next release? Send me your rubygems e-mail/username if you're down to dblock at dblock dot org.

**Comment by mattdsteele** [comment]
Happy to help! I'm kind of cargo-culting my way through Ruby (I've never published a Gem) but I'll send my account info.

If you could update `CONTRIBUTING.md` with the release process (or point me to any other docs), I can work on cutting the next version with these changes, and ping you if I've got any questions.

**Comment by dblock** [comment]
https://github.com/dblock/strava-ruby-cli/blob/master/RELEASING.md
